# Drug intrinsic view
DRUG:
  NODE_IN_FEATS: 75
  PADDING: True
  HIDDEN_LAYERS: [128, 256, 128]
  NODE_IN_EMBEDDING: 128
  MAX_NODES: 290

# Protein intrinsic view
PROTEIN:
  NUM_FILTERS: [128, 128, 128]
  KERNEL_SIZE: [3, 6, 9]
  EMBEDDING_DIM: 128
  PADDING: True

# Self-Attention setting
SELF_ATTENTION:
  HEADS: 4
  HIDDEN_DIM: 356  # 128 + 228
  H_OUT: 256
  OUT_DIM: 128
  DROPOUT: 0.05

# MLP decoder
DECODER:
  NAME: "MLP"
  IN_DIM: 256
  HIDDEN_DIM: 512
  OUT_DIM: 128
  BINARY: 1

# SOLVER
SOLVER:
  MAX_EPOCH: 100
  BATCH_SIZE: 256
  NUM_WORKERS: 0
  LR: 0.0001
  SEED: 47

# RESULT
RESULT:
  OUTPUT_DIR: "./result"
  SAVE_MODEL: True